### ISSUE TITLE
Feature Req - Masking values

### ISSUE THREAD

**Issue by fenneh** [Caiyeon/goldfish#120]
Hey Fellas,

A real small thing, would we be able to "mask" values in the secrets page? The scenario would be if someone is shoulder surfing, you have a bunch of logins stored and don't want them seeing every login on the page.

Whilst I get you could use the vault cli to extract values without doing that, it kind of defeats the point of the UI.

**Comment by Caiyeon** [comment]
I'm not sure what you mean. The CLI would display secrets on the screen as well, so shoulder surfing is still possible.

**Comment by fenneh** [comment]
Hey @Caiyeon - Sure, i'll elaborate a little. 

If you were to say a vault use case is to store usernames and passwords. 

If someone were shoulder surfing you, and you were to use the UI, they'll instantly see every secret on the page. What I'm proposing is the ability to hide the secrets by masking them with ********** and have that toggleable (Per page, per secret). No encryption, no hashing just a simple masking to stop eyes other than your own seeing everything on a page.

**Comment by Caiyeon** [comment]
The CLI is equally vulnerable to this, as is every rest client and other vault ui alternatives. I'm not sure if I want to start protecting the user from physical prying eyes, since that would involve far more work than just starring secrets.

Thank you for the suggestion, but I think this is not in the security model and scope of goldfish.

**Comment by fenneh** [comment]
Sure - will knock something up myself then. Thanks for taking the time to respond.
