### ISSUE TITLE
LDAP login is broken in 0.5.1

### ISSUE THREAD

**Issue by andrewsav-datacom** [Caiyeon/goldfish#128]
LDAP login is working fine in 0.5.0 but is broken in 0.5.1. When you put your username and password and press the login button, you get the toast that login succeeded, but you don't actually sign in and the session details below remain empty. All other pages still ask you to sign in first.

**Comment by andrewsav-datacom** [comment]
This is straight after pressing the Login button:
![2017-07-24_16-33-47](https://user-images.githubusercontent.com/27190911/28508276-0de16258-708e-11e7-915d-0f2466aec300.png)

**Comment by andrewsav-datacom** [comment]
Also, the version number next to the logo has disappeared, but that's probably intentional with bulma upgrade:
![2017-07-24_16-45-05](https://user-images.githubusercontent.com/27190911/28508506-823ed4b8-708f-11e7-98c5-8c26f6247088.png)

**Comment by Caiyeon** [comment]
Indeed, the version number has moved from the navbar to the docs dropdown. Bulma update essentially disabled centered elements in a navbar, so I had to make do.

Could you open up chrome dev console and take a look at what the api response was? With all sensitive strings censored of course. It's a little hard for me to test without an LDAP server myself

**Comment by Caiyeon** [comment]
Nevermind, I see the problem! Will release hotfix soon

**Comment by andrewsav-datacom** [comment]
@Caiyeon thank you!

**Comment by Caiyeon** [comment]
Hotfixed in tag v0.5.1 https://github.com/Caiyeon/goldfish/commit/10a72d1fd4498190922d35b90cd5563c27a51225

Fixed in master https://github.com/Caiyeon/goldfish/commit/e9b879fe680c2b2b692e02866308d095d4e54f2e

Release v0.5.1 has been rebuilt and reuploaded: https://github.com/Caiyeon/goldfish/releases/tag/v0.5.1

Let me know if it still bugs out. Thanks for reporting the issue, and I apologize for the inconvenience of redeploying. Perhaps you have it automated! :)

**Comment by andrewsav-datacom** [comment]
Yep, working now. Thank you for the quick turn-around. @Caiyeon
