### ISSUE TITLE
Question: Starting goldfish without wrapping token, and providing it later

### ISSUE THREAD

**Issue by andrewsav-datacom** [Caiyeon/goldfish#129]
There is a long thread about unattended startup mode for vault [here](https://github.com/hashicorp/vault/issues/72). The consensus is that it is not safe/secure, but vault allows you to do this (without -dev mode) if you want to. For example here is a [sample systemd](https://blog.vivekv.com/hashicorp-vault-systemd-startup-script.html) script for vault.

I would like an option for unattended startup of goldfish. Is this possible? 

Goldfish needs a token (wrapped one use secret) to startup, in order to read (and hot re-read) configuration data and also for access to "cryptography as a service" via the transit backend. [Some other vault UIs](https://github.com/djenriquez/vault-ui) do not require any access to vault at all, except access granted by the end user token. That way you can even up the docker container with the vault UI app with a one-liner, navigate in your browser to your local host, paste your token or other auth backend credentials, and do whatever you need to do and then put the container down. You also have an option of installing the very same application somewhere, where it can _survive reboot_.

Has any thought been given to these two scenarios with regards to goldfish? Maybe goldfish "lite"? I understand that this is probably no mainstream usage, but that could be extremely convenient (at the expense of security), and given that even vault itself is willing to give the user this option, it would be very appreciated if goldfish could too.

_Sidenote: I agree that following the setup notes is extremely easy, but a docker one-liner is even easier_.

**Comment by Caiyeon** [comment]
In terms of security, it is actually secure to have a non-bootstrapped launch mode for goldfish. This is because goldfish takes vault as a source of absolute truth, and all the burden of persistence is within vault. So security isn't a problem.

I have toyed with this idea for awhile now:
1. Goldfish launches without the wrapping token (but still with the static config file)
2. Goldfish serves only a landing page while it is not bootstrapped. This landing page would have an input form for the wrapping token.
3. Operator visits page, puts in wrapping token, and goldfish verifies it by bootstrapped to vault
4. End result is identical to the current deployment

This relieves the burden of the operator by shifting the wrapping token from **provision time** to **operation time**. Which, counts for quite a bit of convenience. In addition, this could go quite well with #81. There could be a simple checkmark to bootstrap with approle (to service a whole team) or a raw token (to service one person)

Unfortunately, I just can't find the time lately to dedicate to such a large overhaul. If I didn't care for code quality, perhaps I could write it badly. But the work required to do it elegantly in the backend would take some refactoring. However, it is possible, and I have thought about it. If I didn't need to sleep, maybe this would've been done already ;)

I'll rename the title and leave this up in case anyone else wants this. Reactions are sufficient for voting.

**Comment by Caiyeon** [comment]
I should clarify: goldfish's vision includes a full fledged request & approval based system. This requires goldfish to have an approle token. The only difference is where in the pipeline this token is given. A local deployment will likely be a feature (#81), but it will only be listening on local host and will not be able to perform requests.

**Comment by andrewsav-datacom** [comment]
To be honest, providing the token _later_ does not solve the issue of unattended startup. I hacked together [this script](https://gist.github.com/andrewsav-datacom/177694f77dafa6f6bfc4b9a30e72c2fd) to do what I want. @Caiyeon 

Thank you for getting some thoughts to it and providing background for your reasoning. It's useful info.

**Comment by Caiyeon** [comment]
I'm a little confused by what you mean with unattended startup. Your script looks more or less what I imagine people use to deploy goldfish now, albeit a little messy. You can checkout the docker compose for a way to launch without manual intervention as well. There is a one-liner to start both vault and goldfish in one go.

If you are asking why you cant "unseal" goldfish statically - goldfish bootstraps to vault using approle. As far as I know, this is the easiest way to setup approle with vault. Goldfish needs its own server token to perform actions such as storing secrets in `cubbyhole`, which is essential to the request system

**Comment by andrewsav-datacom** [comment]
@Caiyeon I don't think we are in a disagreement.  I'm a windows guy, so I'll take the "little messy" part. It's just it took me a few hours to come up with it, since retrieving the wrapped token to provide on the start-up command line for goldfish, is something everyone needs to do, yet there is no "easy" way of doing it, hence - the script. What I was asking for is an easier way to do the same. If not an optional static key, but at least less messier "official" sample script on the wiki to do the same - just a suggestion.

As far as docker goes, this is also a good info, because while I can see the docker related files in the repo, neither readme nor wiki mention anything about docker, (or I missed it), so I assumed that it's not ready for use by general public (me).

**Comment by Caiyeon** [comment]
There is no docker image that can be pulled and added. But there is a docker compose [here](https://github.com/Caiyeon/goldfish/tree/master/docker) that is as close to a production environment as can be (minus certificates)

The wrapping token can be retrieved by a simple command:
`vault write -f -wrap-ttl=20m -format=json auth/approle/role/goldfish/secret-id | jq -r .wrap_info.token`

I feel that your question is more about how to provision your host machine? Where do you host your instances on (AWS?)

**Comment by andrewsav-datacom** [comment]
@Caiyeon thank you for that. Well I did solve my immediate problem with the script I linked. It allows the machine hosting goldfish (private cloud) to be re-booted and not require a human for re-starting the goldfish with s new token (which is retrieved automatically with the command you citing above). So I'm good. Was just thinking about helping the next guy who is in the similar scenario. Thank you for your help.

**Comment by Caiyeon** [comment]
Perfect, glad to hear the problem is solved.

Ideally however, the provisioning of the system is not within the scope of goldfish. Software like hashicorp's own terraform is great for setting up a cloud host with a static config and downloaded binary. Then all you have to do is set an environment variable to the command I pasted above, and `terraform apply` away. In a properly constructed provisioning system, the deployment of goldfish should take no longer than a minute (aside from the provisioning software's time taken)
