### ISSUE TITLE
Question: what is the rationale for using root token for policy changes?

### ISSUE THREAD

**Issue by andrewsav-datacom** [Caiyeon/goldfish#131]
It is possible to change policy without a root token. All you need is an access to the policy path. Yet, goldfish generates a _root token_ for this task.

As I understand this is done to leverage the vault build-in  shamir's secret sharing algorithm to implement remote consensus in goldfish.

That is the task that this implementation solves is to make sure:

a) no single admin can change the policy; and
b) admins can do it remotely if consensus is reached.

To me it looks like if `a)` is not a requirement, then the whole root token thing is not needed. Is this correct understanding?

**Comment by Caiyeon** [comment]
Giving any token the right to write to policies path is essentially creating a pseudo root token. This token can update its own policies to perform any task (I.e. Root token power). Worse yet, this is harder to detect, since you can't simply search for root policy to find such tokens. 

Policies that allow changes to policies should not be allowed under any circumstance, and would break vault's security model
