### ISSUE TITLE
login with vault root token fails

### ISSUE THREAD

**Issue by rohit-kaul** [Caiyeon/goldfish#140]
Hello,

I was trying this out the very first time & tried to follow this

https://github.com/Caiyeon/goldfish/wiki/Production-Deployment

However, after bootstrapping goldfish, when I try to login via the vault root token I get

Error: 500
Goldfish could not use transit key: Error making API request. URL: PUT http://127.0.0.1:8200/v1/encrypt/goldfish Code: 403. Errors: * permission denied 

I am running 3 consul + 2 vault in HA mode.  Is this a known issue? Any ideas?

I don't find anything relevant in vault or goldfish logs

**Comment by Caiyeon** [comment]
Hi,

Did you configure a transit key in the runtime configuration? i.e. `secret/goldfish` key `ServerTransitKey` ? Does the `goldfish` policy have permissions to encrypt and decrypt this key?

You can also disable transit encryption (it is optional) by setting `ServerTransitKey` to be empty string. goldfish will reload settings every minute.

**Comment by rohit-kaul** [comment]
Thanks for replying. Turns out I was missing the transit key. The "permission denied" error threw me off. I ended up looking at vagrant/required.sh to see what was missing in my blind copy of step 1 from https://github.com/Caiyeon/goldfish/wiki/Production-Deployment. Adding vault write -f transit/keys/goldfish fixed it.

**Comment by Caiyeon** [comment]
That's actually a good catch: the wiki writes `ServerTransitKey` but does not initialize the key. I've updated the wiki to clarify this, and updated the policy comments as well 24cff56 

I could solve this problem by giving goldfish policy the right to create transit keys, but I don't feel comfortable making that a general practice (since the service really shouldn't be creating keys)

Cheers
