### ISSUE TITLE
Vuejs Integration

### ISSUE THREAD

**Issue by beatscode** [Caiyeon/goldfish#142]
Hello, I am in the process of learning to integrate a vuejs application with a golang app.
Just reading through the code I see you have

- Separate frontend folder for what looks like a vue-cli app
- npm run build process creates an assets directory 
- go backend seems to mount this assets directory
- 2 systemd services that run the frontend and go based api.

A few questions:

- Are my assumptions correct?
- In your opinion, what are the advantages to this sort of setup.
- Is this common structure for golang + X frontend framework in ?

Personally I always wanted to treat the front and backend separately.

**Comment by Caiyeon** [comment]
The production build script can be found here https://github.com/Caiyeon/goldfish/blob/master/build.sh

The end result is that there is one single binary, with the static folder baked in as code.

The dev environment is different, because `npm run dev` initiates hot-reload.
 
This production build routine guarantees that the frontend static assets folder is not misplaced, mismatched, or missing.

I am not sure what the common structure is. When I started this project, there were 0 large scale golang and vuejs projects out there. So I had to make do.

For future conversations, please try to keep this issues section specific to goldfish & vault issues. At the moment I don't have a general questions forum, but I'd rather not start a FAQ for golang or vuejs in general
