### ISSUE TITLE
Feature Request: Confirm Delete Prompt When Deleting Keys

### ISSUE THREAD

**Issue by ecliptik** [Caiyeon/goldfish#152]
Deleting a key from a Secrets path should have a prompt to "Confirm Delete $PATH/$KEY" with an option for "Don't Prompt This Again" checkbox.

We had a first-time Goldfish user today accidentally delete a path/key when navigating the UI because they thought it would have prompted first.

**Comment by Caiyeon** [comment]
Which version did you deploy?

The confirmation button should exist since 0.6.1 https://github.com/Caiyeon/goldfish/issues/137
![image](https://user-images.githubusercontent.com/6126493/29801468-a60c3ff6-8c24-11e7-80ec-db122c88fcb0.png)

Unfortunately I'm too busy to make proper modals (i.e. popup confirmations), so I think a confirmation button is the only thing in place at the moment.

**Comment by ecliptik** [comment]
A co-worker noticed it today when we were still on 0.6.0, and after putting this issue in I saw 0.7.0 and upgraded, but didn't notice it had changed. Just having a Confirm is much better than not and a pop-up probably isn't necessary, thank you.

**Comment by Caiyeon** [comment]
No problem. While I am a fan of nice prompts, popups just take too much time. Maybe someday.

Let me know if there are other inconveniences or unexpected behaviours

Cheers
