### ISSUE TITLE
Allow `tls_require_and_verify_client_cert` to be enabled in vault

### ISSUE THREAD

**Issue by michaelw** [Caiyeon/goldfish#156]
Goldfish currently seems to require vault to turn off `tls_require_and_verify_client_cert`.  With the following config, I get the error below:
```hcl
listener "tcp" {
  # ...
  tls_require_and_verify_client_cert = "true"
}
```

Error:
```
2017/09/11 08:21:44 [ERROR]:  Get https://vault.XXX:8200/v1/sys/health: remote error: tls: bad certificate
{"time":"2017-09-11T08:21:44.284406561Z","id":"","remote_ip":"10.x.y.z","host":"goldfish.XXX","method":"GET","uri":"/v1/vaulthealth","status":500, "latency":178592316,"latency_human":"178.592316ms","bytes_in":0,"bytes_out":106}
```

Note that curling the health endpoint succeeds if presenting a valid client cert:
```
curl --cert goldfish+ca.crt --key goldfish.key https://vault.XXX:8200/v1/sys/health
```

(BTW: thanks for goldfish, it's pretty awesome!)

**Comment by Caiyeon** [comment]
You are sure that if vault has that key turned off in configuration, goldfish works as expected?

In that case I'm fairly certain what the problem is. Goldfish does not currently use the provided certificate in sending requests to vault. At the moment they are only used for the server.

I would classify this as a bug, but I'm unsure if I can give you a timeline to getting this fixed (there might be a bit of restructuring to get the certificate all the way down to the http requests)

**Comment by Caiyeon** [comment]
@michaelw are you planning to stick with the `tls_require_and_verify_client_cert` key in vault? This would require every end-user to also authenticate with a certificate. I'm not sure I've seen this setup before, simply because it causes end users too much pain

**Comment by Caiyeon** [comment]
On further thought, I would not classify this as a bug. Using the provided certificate to talk to vault means that the end user will be using goldfish's certificate as a part of their identity. This defeats the purpose of requiring a client certificate, and it's a catch 22. I have no current plans to implement this for now, although it is possible (and seems to be quite easy) to do so using vault's official API.
