### ISSUE TITLE
creating new mounts?

### ISSUE THREAD

**Issue by airtonix** [Caiyeon/goldfish#172]
How's this done? the entrypoint.sh? the hcl? cli?

Basically I need to support concourse.ci which reads secrets off `/api/concourse/*` not `/api/secrets/concourse`

You can't change where concourse looks, so I need a new mount.

**Comment by Caiyeon** [comment]
I'm not sure what you mean. If you mean creating entirely new mounts in vault, that's currently not supported in goldfish. You'll have to do that with the CLI.

**Comment by eljefedelrodeodeljefe** [comment]
I kind of agree with the @airtonix. One would want to change the path here, to the other mounts to actually access them.

Afaik, it's rather uncommon to group everything under a single mount `secret`.

E.g. I believe what goldfish is currently doing is `vault read secret/goldfish/`, but does not a allow for `vault read postgresql/`

Interestingly it does allow that for the full path, but not the mount root, so I guess it's some kind of unhandled error around permissions.

<img width="924" alt="goldfish" src="https://user-images.githubusercontent.com/3899684/34473909-bc4d87a4-ef78-11e7-8066-95b991175803.png">
<img width="951" alt="goldfish" src="https://user-images.githubusercontent.com/3899684/34473912-c15779e4-ef78-11e7-99aa-2cad3e77883b.png">

**Comment by eljefedelrodeodeljefe** [comment]
cc @Caiyeon

**Comment by Caiyeon** [comment]
There is no bias from goldfish's side in secrets. You are attempting to read `postgres`, which is not a valid endpoint to read from, since `postgres` is a mount, not a secret. The original issue asked about creating mounts, which is currently not supported. Reading/writing/listing secrets are fully supported.

I think you are confusing the difference between secret and path when it comes to Vault. They can be denoted by the trailing slash.

**Comment by peterchoo** [comment]
@Caiyeon Do you have plans to be able to manage mounts through goldfish?

**Comment by Caiyeon** [comment]
There are no immediate plans to allow creating/deleting mounts. Configuring them is already supported. There are other priority issues and I'm short on time recently.
