### ISSUE TITLE
Goldfish server is not stateless

### ISSUE THREAD

**Issue by OverlyExcessive** [Caiyeon/goldfish#179]
We have been running Goldfish in our Swarm cluster and we have noticed that whenever Goldfish is rescheduled, for instance when we are performing a rolling update or similar, goldfish frontend will report that it has not been bootstrapped even though the `secret/goldfish` key is still present. Meaning that a Vault admin has to manually repeat the bootstrapping process everytime Goldfish is scheduled.

**Comment by Caiyeon** [comment]
I believe docker swam rescheduling simply relaunches the container, which means goldfish process restarts. This is expected behavior. Goldfish is entirely in-memory, so when you restart the process, it forgets everything. `Bootstrapping` goldfish simply means to give it a vault approle token, in order for it to have access to vault. If this token is re-used or recycled, there's a risk of compromising everything in goldfish. Therefore, giving goldfish a new approle token every launch is the expected behavior.

There's a couple of things you can do to make this more automatic. Goldfish accepts bootstrapping in 3 places. 
1. At launch time, using `-token` cmd line arg
2. After launch, in the UI
3. After launch, via HTTP request to `/v1/bootstrap`. Catch the request in chrome dev tools for a full example

If vault operations are already hooked into the docker swarm orchestration, this process should be fairly easy to automate.
