### ISSUE TITLE
edit json data

### ISSUE THREAD

**Issue by frandriamora** [Caiyeon/goldfish#201]
Hi

I want to use json format to store the secrets in vault. The json data display correctly in goldfish, but it seems I cannot edit / change them. It just says: Object. Any tip?

Frederic

Best regards

**Comment by frandriamora** [comment]
More info:

- When displaying the json, the display of the value for the key is correct, like so:
{ "bacula__xxxx__xxxx__xxxx": "<password here>", "bacula__zzzz_zzzzz": "<password here>", "bacula__yyyy_yyyy": "<password here>" }

- When editing the secret, the key is correct, but the value shows like this:
[object Object]

- When editing that value, it is treated litterally like a string, so I can modify it and save it like "[Object O" for example, but then the value becomes a string and is no longer a json structure

Thanks

**Comment by Caiyeon** [comment]
Reading and writing values as json objects instead of strings is currently not supported. It's partially due to a limitation in vuejs `v-model` directive, but also due to the secrets page never being designed with this in mind. Perhaps one day there will be a refactor which allows editing an entire secret textbox-style, but at the moment there are no such plans
