### ISSUE TITLE
Feature request: Vault rekey

### ISSUE THREAD

**Issue by billyaustin84** [Caiyeon/goldfish#208]
Hi,

It would be a really useful feature to be able to initiate and manage a rekey operation from with Goldfish

**Comment by Caiyeon** [comment]
I don't see the rekeying operation being implemented anytime soon. This is because of the critical nature of the rekey process, and how rarely it should be performed. Goldfish is only able to notify the very last user of the unseal key set, which means that if 3 users re-key, and the last user's chrome crashes, vault could be unrecoverable.
