### ISSUE TITLE
information on the users page

### ISSUE THREAD

**Issue by karstensi** [Caiyeon/goldfish#210]
We are working on our work-flow with vault and are looking for at UI to vault, this seems great. 
As we are deploying apps with approle it would be great to be able to display the role_id in the tokens overview page. 
Alternative go get the information in the information regarding tokens, that seems to be under development. 

Thanks,

**Comment by Caiyeon** [comment]
Role_ids will not be displayed in the token overview page because it hardly applies to most tokens.
I have been meaning to implement the detailed modal view properly, and I think this is sufficient.
You will be able to see this in the full v0.8.0 release.
![image](https://user-images.githubusercontent.com/6126493/33856042-b1656522-de7b-11e7-8a24-0db2f827bc4f.png)
