### ISSUE TITLE
Feature request: Support multiline pasted values

### ISSUE THREAD

**Issue by dswhite42** [Caiyeon/goldfish#234]
Goldfish does not (easily) support pasting in preformatted multiline strings as values.  If you paste a multiline string, it will go in as one long line with the newlines removed.

There is a workaround:
1. Create a new key/value pair.  Leave the value blank.
2. Press <ENTER>.  Goldfish will remove focus from the row and start a new empty row.
3. Click on the value you left blank to return focus to that field.  Press SHIFT-ENTER.  This seems to put Goldfish into multiline mode.
4. Paste your multiline value.  It should go in with newlines intact.
5. Return to the top of the value field and delete the newline that pressing SHIFT-ENTER created.  
6. Save the secret.

Maybe there's a way to configure Goldfish so that the workaround isn't necessary?

Thanks.

**Comment by Caiyeon** [comment]
Proposed fix:
* Change every input in secrets page to textarea instead of input (right now the boxes switch back and forth depending on shift+enter)
* When focused on the last value box, pressing `tab` should trigger a new key value entry. Currently, pressing enter triggers it, but this wouldn't work on a textarea box.
* The tooltip `Shift + enter to insert multiple lines` should be changed to perhaps `Press tab to create a new key pair`

Some of these changes will include removing deprecated code
