### ISSUE TITLE
Feature request: Security Trimmed UI

### ISSUE THREAD

**Issue by oaustegard** [Caiyeon/goldfish#243]
### Feature request: Security Trimmed UI

Is this a front-end feature or backend? (or both?) both: front-end experience, back-end implementation

Description of feature: As a user, I would like to only see the menu items that I have access to given my current log-in state

Are you able to submit a pull request for this feature?
No

**Comment by Caiyeon** [comment]
Finding all the things a user has access to is non-trivial, and would require an excessive number of queries every login. Also, this would not be reactive. If permissions change, there's no way to react in a feasible manner.

As of now, certain pages will detect user's capabilities and act accordingly (the token creator, for example) but that is because goldfish already has definitive information to work with. This is not the case for the entire menu.

I see no possibility of this being implemented.
