### ISSUE TITLE
Bug: demo token doesn't work

### ISSUE THREAD

**Issue by dylanfoster** [Caiyeon/goldfish#250]
Goldfish version: demo

Operating system: osx

Steps to reproduce:

- go to demo site
- go to login
- enter `goldfish` in token authentication

Expected behaviour:

user is logged in

Actual behaviour:

403

**Comment by Caiyeon** [comment]
Presumably someone clicked the newly added "revoke token" button. I'll see if I can deny the token this permission, but I'm not 100% sure it's possible. If not, the demo will have to be altered.

**Comment by Caiyeon** [comment]
This has been fixed by the addition of an explicit deny permission to the public demo token.

Interestingly, this reveals an edge case of when the user is not permitted to revoke itself, which is very very rarely the case. There is a minor frontend bug when this occurs, and this will be fixed on the next release. Thanks for the report!
