### ISSUE TITLE
many error "TLS handshake error from <ip>: EOF"

### ISSUE THREAD

**Issue by gsanchez-uz** [Caiyeon/goldfish#273]
### Bug report:

Vault version: 0.9.0

Goldfish version: 0.7.3

Operating system: CentOS 7.4

On my goldfish docker appears many logs with next text every minute:

URL: GET https://analytics0-pro-usa.userzoom.com:8200/v1/secret/goldfish
Code: 403. Errors:

* permission denied
echo: http: TLS handshake error from 172.24.32.132:37512: EOF
echo: http: TLS handshake error from 172.24.32.132:37544: EOF
echo: http: TLS handshake error from 172.24.32.132:37572: EOF
echo: http: TLS handshake error from 172.24.32.132:37608: EOF
2018/04/25 10:17:18 [ERROR]:  Error making API request.

Do you know if consul or vault does requests to https://domainname:8200/v1/secret/goldfish for health checks'

**Comment by Caiyeon** [comment]
Hi there,

v0.7.3 was quite a long time ago, and I would suggest you upgrade to the latest version. The TLS errors you see are from networking issues, and not caused by goldfish. Something (misconfiguration in networking?) is causing invalid http requests.

Regarding health checks, there have been no tests on how health checking can be done.
