### ISSUE TITLE
Whitespace added at end of copied string from UI

### ISSUE THREAD

**Issue by dkorel-copperleaf** [Caiyeon/goldfish#274]
### Bug report:

in Chrome, when highlighting and copying a value (secret), it appears to append whitepace to the end of the string

Vault version:

Goldfish version: 0.9.0

Operating system: Windows / Chrome

Steps to reproduce: highlight and copy a value

Expected behaviour: only the value is copied

Actual behaviour: value + whitepace is copied

### Feature request:

Is this a front-end feature or backend? (or both?)

Description of feature:

Are you able to submit a pull request for this feature?

**Comment by Caiyeon** [comment]
What do you mean by "password value"? If you mean the value in secrets page, I cannot reproduce this issue.

**Comment by dkorel-copperleaf** [comment]
When selecting a value by double clicking, then copying - a tab char is appended

**Comment by Caiyeon** [comment]
I cannot reproduce this by double clicking, copy, and pasting the value.

If you mean highlighting the entire value by dragging your mouse over it, then yes there is a tab preceding the value. This is a "feature" of HTML tables. It exists so that when you copy multiple columns, there is a tab character separating each column, for clarity.

If the latter behavior is what you're referring to (a tab character in front of the value), this is standard browser behavior for tables. You may test this theory on sample tables here: https://bulma.io/documentation/elements/table/

**Comment by dkorel-copperleaf** [comment]
The value is appended rather than prepended. But I think this is what you mean, and yes it appears to be a default behavior of HTML tables. Easy to avoid once known.

**Comment by Caiyeon** [comment]
If this is the default behaviour of HTML, I am not willing to make workarounds. You may wish to try Vault's builtin UI. Perhaps their copy & paste mechanism is closer to what you are looking for :)
