### ISSUE TITLE
cert_file flag is unrecognized

### ISSUE THREAD

**Issue by kevinjcash** [Caiyeon/goldfish#35]
I'm trying to start goldfish and pass the cert and key for TLS on the CLI, but it fails with the error `flag provided but not defined: -cert_file`. I can clearly see the cert_file flag defined in server.go. These appear to be the flags it has defined:
```
Usage of goldfish:
  -approle_path string
        The approle mount's login path (default "auth/approle/login")
  -config_path string
        A generic backend endpoint to store run-time settings. E.g. 'secret/goldfish'
  -dev
        Set to true to save time in development. DO NOT SET TO TRUE IN PRODUCTION!!
  -role_id string
        The approle role_id (default "goldfish")
  -vault_addr string
        Vault address (default "http://127.0.0.1:8200")
  -vault_token string
        The approle secret_id (must be in the form of a wrapping token)
```

**Comment by Caiyeon** [comment]
Well this is what I get for writing code close to midnight.

This is caused by https://github.com/Caiyeon/goldfish/commit/edd6b1dae29fcbdda6c2ced228656a5b15f519e2#diff-34c6b408d72845d076d47126c29948d1R80

I forgot that go can't parse args twice, so the `cert_file` was not defined in the first `flags.Parse()`, and hence the error.

A temporary workaround if you need this fixed right away:
* hardcode these three string variables https://github.com/Caiyeon/goldfish/blob/master/server.go#L76
* remove the `flag` lines, and remove `flag` import https://github.com/Caiyeon/goldfish/blob/master/server.go#L4

A proper fix will involve a small restructure of how the main package and vault packages talk to each other. I'll add this to my evening to-dos. Apologies for the inconvenience.

**Comment by kevinjcash** [comment]
No problem, thank you for the quick reply. I'll use the hardcode workaround for now. Looking forward to working with this, seems like a promising project. 👍
