### ISSUE TITLE
Multiple Vaults

### ISSUE THREAD

**Issue by dasJ** [Caiyeon/goldfish#76]
We have a Cluster consisting of multiple Vault instances for fault-tolerance.
It seems like goldfish can only use one Vault (I cannot see any documentation saying otherwise).
It would be useful if a user could configure multiple Vault addresses so there is either a dropdown to select the instance, or Goldfish could automatically connect to the first available Vault.

**Comment by Caiyeon** [comment]
If you bootstrap goldfish to the vault instance that is not current the leader, then goldfish should function correctly. Every request would get forwarded to the leader and if the leader goes down, the follower will still be available. In your cluster setup, is there not a preferred leader node?

**Comment by Caiyeon** [comment]
Would it be possible to launch multiple copies of goldfish, listening at different addresses and connected to different vaults (essentially, different config files). Each one could listen at a different port, and the default one could be regular https (443).

The downside would be that sessions arent stored across instances, and request system would not transfer across instances.

**Comment by dasJ** [comment]
Yes, that would be the workaround I thought of. Maybe dynamically generating some nginx configuration so it automatically switches when a Vault goes down.
I currently have 3 Vaults, where one is the leader. I could configure Goldfish to use one of the leaders, but that would mean I couldn't use the third one and I could also not use Goldfish when the follower goes down.

**Comment by Caiyeon** [comment]
Quite honestly the easiest way is to make sure your deployment for goldfish is as one-click as possible. If you are using terraform or some other provisioner, this should be fairly simple. And it would help in the case where goldfish goes down or you want to try upgrading to a new version.

But I do agree this would be a nice-to-have. The configuration file format can be specified with multiple vaults, but goldfish rejects config files with more than 1 vault instances right now, because there's no logic for verifying that they are the same cluster, and no logic to perform a seamless switch over. Although, I have considered a header in the API to specify a `preferred-vault` perhaps.

Either way, this is quite a distance away from the current roadmap. I'll reopen this when more urgent features have been solidified.
